def VENV = 'team-bot-venv'
def DAILY_CHANNELS = [
  'team-central',
  'dev-squad-bookworm',
].join(' ');

pipeline {

  agent {
    label 'general'
  }

  triggers {
    cron('H 0 * * 1-5')
  }

  environment {
    MATTERMOST_HOOK_URL = credentials("mattermost-teambot-hook")
  }

  stages {

    stage ('Prepare') {
      steps {
        script {
          currentBuild.description = "Teambot run for the daily scrum"
        }
        checkout scm
        sh "${WORKSPACE}/jenkins/prepare-virtualenv.sh ${VENV}"
      }
    }

    stage ('Run') {
      environment {
        GITHUB_CREDS = credentials('github-jenkins-wazo-bot')
      }
      steps {
        sh """
          . ${VENV}/bin/activate
          python3 ./agenda.py daily-scrum/planning.yaml '$MATTERMOST_HOOK_URL' $DAILY_CHANNELS
        """
      }
    }
  }

  post {
    failure {
      mattermostSend color: "danger", message: "Teambot [failed :nuke:](${BUILD_URL}/console)"
    }
  }
}
