def DAILY_CHANNELS = [
  'team-central',
  'dev-squad-whitelabel',
  'dev-squad-user-management',
  'dev-squad-microsoft-teams'
].join(' ');

pipeline {

  agent any

  triggers {
    cron('H 0 * * 1-5')
  }

  environment {
    MATTERMOST_HOOK_URL = credentials("mattermost-teambot-hook")
  }

  stages {

    stage ('Prepare') {
      steps {
        script {
          currentBuild.description = "Teambot run for the daily scrum"
        }
        checkout scm
        sh 'pip3 install -r requirements.txt'
      }
    }

    stage ('Run') {
      environment {
        GITHUB_CREDS = credentials('github-jenkins-wazo-bot')
      }
      steps {
        sh "python3 ./agenda.py daily-scrum/planning.yaml '$MATTERMOST_HOOK_URL' $DAILY_CHANNELS"
      }
    }
  }

  post {
    failure {
      mattermostSend color: "danger", message: "Teambot [failed :nuke:](${BUILD_URL}/console)"
    }
  }
}
