def venv = 'team-bot-venv'
pipeline {

  agent any

  triggers {
    cron('H 0 * * 1-5')
  }


  stages {

    stage ('Prepare') {
      steps {
        script {
          currentBuild.description = "Teambot run for the sprint review"
        }
        checkout scm
        sh "${WORKSPACE}/jenkins/prepare-virtualenv.sh ${venv}"
      }
    }

    stage ('Run') {
      environment {
        MATTERMOST_HOOK_URL = credentials("mattermost-teambot-hook")
      }
      steps {
        sh """
          . ${venv}/bin/activate
          python3 ./agenda.py sprint-review/planning.yaml "$MATTERMOST_HOOK_URL" developpement
        """
      }
    }
  }

  post {
    failure {
      mattermostSend color: "danger", message: "Teambot [failed :nuke:](${BUILD_URL}/console)"
    }
  }
}
