pipeline {

  agent any

  triggers {
    cron('00 10 * * 1-2')
  }

  environment {
    MATTERMOST_HOOK_URL = credentials("mattermost-teambot-hook")
  }

  stages {

    stage ('Prepare') {
      steps {
        script {
          currentBuild.description = "Teambot run for the release"
        }
        checkout scm
        sh "${WORKSPACE}/jenkins/prepare-virtualenv.sh ${venv}"
      }
    }

    stage ('Run') {
      environment {
        GITHUB_CREDS = credentials('github-jenkins-wazo-bot')
      }
      steps {
        sh """
          . ${venv}/bin/activate
          python3 ./agenda.py release/planning.yaml "$MATTERMOST_HOOK_URL" release
        """
      }
    }
  }

  post {
    failure {
      mattermostSend color: "danger", message: "Teambot [failed :nuke:](${BUILD_URL}/console)"
    }
  }
}
